<a href="https://colab.research.google.com/github/TejashShah/Pytorch/blob/main/PyTorch_Refresh_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
from pprint import pprint as pp

tensor = torch.ones(4,4)
pp(tensor)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [3]:
import torch
import numpy as np
from pprint import pprint as pp

tensor = torch.ones(4,4)
pp(tensor)
tensor[:,1] = 0 
pp(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [7]:
t1 = torch.cat([tensor, tensor],  dim= 0)
pp(t1)
t2 = torch.cat([tensor, tensor], dim =1)
pp(t2)

t3 = tensor.mul(tensor)
pp(t3)

t4 = tensor.matmul(tensor)
pp(t4)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])


In [10]:
from torchvision.models.vision_transformer import Weights
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1,1000)


Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 204MB/s]


In [16]:
prediction = model(data)
loss = (prediction - labels).sum()
loss.backward()
pp(len(prediction))
pp(len(labels))
pp(type(labels))

1
1
<class 'torch.Tensor'>


In [17]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)
optim.step()

#Gradient example

In [19]:
import torch
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [22]:
Q = 3*a**3 - b**2
pp(Q.sum())

tensor(53., grad_fn=<SumBackward0>)


In [23]:
Q.sum().backward()

In [24]:
pp(a.grad)


tensor([36., 81.])


In [25]:
pp(b.grad)

tensor([-12.,  -8.])


In [29]:
pp(9*a**2 == a.grad)
pp(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
